eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
management:
  metrics:
    export:
      zipkin:
        baseUrl: ${ZIPKIN_URL:http://zipkin-svc:9411}/api/v2/spans
        enabled: true
  tracing:
    brave:
      enabled: true
      sampler:
        rate: 1.0
      spans:
        compression-enabled: true
